### ISSUE TITLE
Add to Releases appImage to download

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ivan-hc/Steam-appimage#1]

**Comment by ivan-hc** [comment]
Is this working well for you?

**Comment by vitaly-zdanevich** [comment]
I did not try.

**Comment by ivan-hc** [comment]
So you have not seen that is already available as pre-release https://github.com/ivan-hc/Steam-appimage/releases

Pre-release because it is an experimental release, I still wait feedbacks to made it stable.
