### ISSUE TITLE
Please consider making the same appImage for battle.net

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ivan-hc/Steam-appimage#14]
<3

**Comment by ivan-hc** [comment]
I'm not a gamer, and all I know about battle.net is from the option of my Diablo II LOD, from year 2000.

But I think that if there is an Arch Linux package for this, its enough to fork or copy this repo and change all "steam" references for what you're looking for.

@Samueru-sama what do you think about?

**Comment by Samueru-sama** [comment]
Isn't battle.net something that needs wine?

**Comment by vitaly-zdanevich** [comment]
I believe yes - battle.net needs Wine.

**Comment by Samueru-sama** [comment]
> I believe yes - battle.net needs Wine.

I that case I think you can use the Steam appimage already to use the battle.net installer. Steam lets you run external windows programs as well akin to wine using proton.

**Comment by vitaly-zdanevich** [comment]
Wow, thanks, I tried, got

> ERROR: ld.so: object '/home/vitaly/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.

**Comment by vitaly-zdanevich** [comment]
THANKS! Battle.net started, installing StarCraft Remastered now...

**Comment by Samueru-sama** [comment]
> THANKS! Battle.net started, installing StarCraft Remastered now...

If you still get errors you might wanna try the bottles appimage that Ivan has, since iirc bottles are made to target these kind of scenarios.

**Comment by ivan-hc** [comment]
@vitaly-zdanevich I've just reduced Bottles from 648 to 550 MB

if this is the solution for you, please close this issue
