### ISSUE TITLE
Warning about locales

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ivan-hc/Steam-appimage#20]
![image](https://github.com/user-attachments/assets/3301faad-ae2b-43ef-825e-e57ba60b59c9)

On running Rexaura game. It works, just warning.

**Comment by ivan-hc** [comment]
is this happening with other games too?

the AppImage mounts /usr/local/lib by default, so Steam uses your system locale

**Comment by vitaly-zdanevich** [comment]
> is this happening with other games too?

Only with Rexaura game.

**Comment by vitaly-zdanevich** [comment]
I believe that my locale is default for Gentoo Linux.

**Comment by ivan-hc** [comment]
have you tried to see if this is a known issue?

**Comment by vitaly-zdanevich** [comment]
Currently on my computer:

```
$ cat /etc/locale.gen 

C.UTF8 UTF-8
```

Is it a bad value?

**Comment by vitaly-zdanevich** [comment]
> have you tried to see if this is a known issue?

No, where? On Steam issue tracker?

**Comment by ivan-hc** [comment]
> Currently on my computer:
> 
> ```
> $ cat /etc/locale.gen 
> 
> C.UTF8 UTF-8
> ```
> 
> Is it a bad value?

no, it is ok



> > have you tried to see if this is a known issue?
> 
> No, where? On Steam issue tracker?

maybe, or also on other forums

if you face this issue with one game over a lot of others, so the issue should be the game

**Comment by vitaly-zdanevich** [comment]
Solved by adding `en_US.UTF-8 UTF-8` to `/etc/locale.gen` and running `locale-gen`.

According to https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Base#Configure_locales

**Comment by ivan-hc** [comment]
good to know, thanks
