### ISSUE TITLE
Armies of Exigo: "The graphics system cannot set display mode" :(

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ivan-hc/Steam-appimage#21]
The game from https://drive.google.com/drive/folders/1dtv5kDnwyWBdSenKCr7KUtvJOr2LSs-I

I love this game, but cannot run it, I tried Bottles too - cannot start, even without an error, nothing special in logs :(

I have AMD GPU, in Bottles tried AMD iGPU.

If you have AMD GPU - is it works for you? 
![image](https://github.com/user-attachments/assets/e0bbf0b8-8c83-4a5e-a128-165260503b9d)

**Comment by vitaly-zdanevich** [comment]
Solved by using only one display (I have 4).

> it is safer to download and install them from there

Nobody sells Armies of Exigo anymore.

**Comment by ivan-hc** [comment]
> Nobody sells Armies of Exigo anymore.

I play 0ad, is open source

**Comment by vitaly-zdanevich** [comment]
But Armies of Exigo is an abandonware :(

You can sign my petition https://www.change.org/p/the-game-armies-of-exigo-from-2004-it-abandonware-so-please-make-it-free-and-open-source
