### ISSUE TITLE
Appimage tested, two issues.

### ISSUE THREAD

**Issue by Samueru-sama** [ivan-hc/Steam-appimage#3]
The appimage launches, the steam interface works and updates work. But that where the good ends haha. 

There's a broken systray icon for steam.

And I cannot launch games, I get this error: 

`Python path configuration:
  PYTHONHOME = '/tmp/.mount_Steam.uLyKsw/usr/:/tmp/.mount_Steam.uLyKsw/usr/lib/python*/'
  PYTHONPATH = '/tmp/.mount_Steam.uLyKsw/usr/share/pyshared/:/tmp/.mount_Steam.uLyKsw/usr/lib/python*/:'
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/tmp/.mount_Steam.uLyKsw/usr'
  sys.base_exec_prefix = '/tmp/.mount_Steam.uLyKsw/usr/lib/python*'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/tmp/.mount_Steam.uLyKsw/usr'
  sys.exec_prefix = '/tmp/.mount_Steam.uLyKsw/usr/lib/python*'
  sys.path = [
    '/tmp/.mount_Steam.uLyKsw/usr/share/pyshared/',
    '/tmp/.mount_Steam.uLyKsw/usr/lib/python*/',
    '',
    '/tmp/.mount_Steam.uLyKsw/usr/lib/python39.zip',
    '/tmp/.mount_Steam.uLyKsw/usr/lib/python3.9',
    '/tmp/.mount_Steam.uLyKsw/usr/lib/python*/lib/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007267b4b40f80 (most recent call first):
<no Python frame>
Uploaded AppInterfaceStats to Steam

(steam:376179): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed

(steam:376179): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
`

**Comment by ivan-hc** [comment]
Thank you, you're the first tester I have here, in this repository.

For what I can see, there is a problem in finding the python libraries.

I've just updated the script to find the main python directory on the host, in /usr/lib.

Try now.

**Comment by Samueru-sama** [comment]
> Thank you, you're the first tester I have here, in this repository.
> 
> For what I can see, there is a problem in finding the python libraries.
> 
> I've just updated the script to find the main python directory on the host, in /usr/lib.
> 
> Try now.
> 
> EDIT:
> 
> https://github.com/ivan-hc/Steam-appimage/releases/download/continuous/Steam-202402140011-x86_64.AppImage

Game does not launch still. 

Some errors that happen when launching steam (missing vulkan is the most likely culprit). 

```
Vulkan missing requested extension 'VK_KHR_surface'.
Vulkan missing requested extension 'VK_KHR_xlib_surface'.
BInit - Unable to initialize Vulkan!
Vulkan missing requested extension 'VK_KHR_surface'.
Vulkan missing requested extension 'VK_KHR_xlib_surface'.
BInit - Unable to initialize Vulkan!
BRefreshApplicationsInLibrary 1: 5ms

(steam:758440): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
BuildCompleteAppOverviewChange: 191 apps
RegisterForAppOverview 1: 9ms
RegisterForAppOverview 2: 10ms

(steam:758440): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed
```

And when trying to launch a game, it still says this: 

Python path configuration:
  PYTHONHOME = '/tmp/.mount_Steam.cXfZPV/usr'
  PYTHONPATH = '/usr/lib/python3.11:'
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/tmp/.mount_Steam.cXfZPV/usr'
  sys.base_exec_prefix = '/tmp/.mount_Steam.cXfZPV/usr'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/tmp/.mount_Steam.cXfZPV/usr'
  sys.exec_prefix = '/tmp/.mount_Steam.cXfZPV/usr'
  sys.path = [
    '/usr/lib/python3.11',
    '',
    '/tmp/.mount_Steam.cXfZPV/usr/lib/python39.zip',
    '/tmp/.mount_Steam.cXfZPV/usr/lib/python3.9',
    '/tmp/.mount_Steam.cXfZPV/usr/lib/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fd451521f80 (most recent call first):
<no Python frame>
Uploaded AppInterfaceStats to Steam

(steam:758440): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed

(steam:758440): GLib-GIO-CRITICAL **: g_settings_schema_source_lookup: assertion `source != NULL' failed

**Comment by ivan-hc** [comment]
Can you extract the AppImage and comment the "export PYTHON*" lines in the AppRun script?
```
./*AppImage --appimage-extract
```
and then execute the AppRun
```
./AppRun
```
see if something changes.

**Comment by Samueru-sama** [comment]
> Can you extract the AppImage and comment the "export PYTHON*" lines in the AppRun script?
> 
> ```
> ./*AppImage --appimage-extract
> ```
> 
> and then execute the AppRun
> 
> ```
> ./AppRun
> ```
> 
> see if something changes.

That "works" now the game proceeds a bit further.

Now I'm met by this window, which the likely reason is due to the missing vulkan errors: 

![image](https://github.com/ivan-hc/Steam-appimage/assets/36420837/a397fc89-9ccf-4e58-9acb-06ba07554cf1)

**Comment by ivan-hc** [comment]
Well, try this other build

https://github.com/ivan-hc/Steam-appimage/releases/download/continuous/Steam-202402141301-x86_64.AppImage

this is the internal AppRun
```
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
export PATH=/usr/bin/:"${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${HERE}"/bin/:"${HERE}"/opt/steam/:"${HERE}"/sbin/:"${PATH}"
export LD_LIBRARY_PATH=/lib/:/lib64/:/lib32/:/usr/lib/i386-linux-gnu/:/usr/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib/:"${HERE}"/lib/:"${LD_LIBRARY_PATH}"
export XDG_DATA_DIRS=/usr/share/:"${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
exec ${EXEC} "$@"
```
here I have also exported XDG_DATA_DIR from the host

**Comment by Samueru-sama** [comment]
> Well, try this other build
> 
> https://github.com/ivan-hc/Steam-appimage/releases/download/continuous/Steam-202402141301-x86_64.AppImage
> 
> this is the internal AppRun
> 
> ```
> #!/bin/sh
> HERE="$(dirname "$(readlink -f "${0}")")"
> export UNION_PRELOAD="${HERE}"
> export PATH=/usr/bin/:"${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/usr/games/:"${HERE}"/bin/:"${HERE}"/opt/steam/:"${HERE}"/sbin/:"${PATH}"
> export LD_LIBRARY_PATH=/lib/:/lib64/:/lib32/:/usr/lib/i386-linux-gnu/:/usr/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib/:"${HERE}"/lib/:"${LD_LIBRARY_PATH}"
> export XDG_DATA_DIRS=/usr/share/:"${HERE}"/usr/share/:"${XDG_DATA_DIRS}"
> EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
> exec ${EXEC} "$@"
> ```
> 
> here I have also exported XDG_DATA_DIR from the host

Now it works, I'm able to launch games!

The systray icon was also fixed by this.

**Comment by Samueru-sama** [comment]
Btw it would be great to have a junest version of this appimage with all the 32bit libraries included.

**Comment by ivan-hc** [comment]
I've already tried to respect this rule, invain, Steam still checks for 32bit libraries on the host, also if they are included on the guest. I don't know where I'm wrong :(

Could you try to build it by yourself? Maybe you are luckyer than me https://github.com/ivan-hc/ArchImage

**Comment by ivan-hc** [comment]
PS: thank you for all tests, I was waiting someone from too much time! Thank you! Thank you ! Thank you!
