### ISSUE TITLE
Stopped Nvidia Handler driver install and now Conty is stuck

### ISSUE THREAD

**Issue by Peppernrino** [ivan-hc/Steam-appimage#34]
I installed the package through AM Application Manager, and during the Nvidia Handler install portion I freaked out and stopped it, because I already have Nvidia drivers installed. Then I decided it would probably be a seperate bundled version somewhere and to dive in...

Now when I type steam in terminal, it says:

Running Conty
Nvidia driver is currently installing
Please wait a moment and run Conty again

I have waited a moment, and tried again. It seems to be stuck. Any ideas?

**Comment by ivan-hc** [comment]
Remove ~/.local/share/Conty and retry

**Comment by Peppernrino** [comment]
I came back to say I tried just that! lol worked like a charm. thank you. :)

**Comment by Samueru-sama** [comment]
>during the Nvidia Handler install portion I freaked out and stopped it, because I already have Nvidia drivers installed

Conty needs to download the nvidia drivers because the nvidia libs in conty have to match the kernel the driver version.

**Comment by Samueru-sama** [comment]
@Peppernrino There has been some changes on how the AppImage handles the nvidia drivers but we aren't sure these work, can you confirm that it does?

**Comment by ivan-hc** [comment]
To be sure you need to remove the ~/.local/share/Conty directory and run the new AppImage
