### ISSUE TITLE
Games won't launch

### ISSUE THREAD

**Issue by IndigoGollum** [ivan-hc/Steam-appimage#35]
The only game i have installed at the moment is Terraria, a game that should run fine on Linux.

On launching it, it says it's launching, says it's running, and then stops with no indication of any error.

I'm using Linux Mint Xfce 22 and running Steam from an external drive.

**Comment by Samueru-sama** [comment]
Hi, does this issue not happen when trying the native Steam package in mint?

Can you open Steam from the terminal and then try to launch terraria?

**Comment by IndigoGollum** [comment]
The native package won't install right. Terraria still doesn't launch but now i can see that it's because there's a space in the drive's name.

**Comment by Samueru-sama** [comment]
> The native package won't install right. Terraria still doesn't launch but now i can see that it's because there's a space in the drive's name. Renaming the drive fixed it.

That's good to hear, this issue can be closed then.
