### ISSUE TITLE
Can you support run on ARM Linux

### ISSUE THREAD

**Issue by iHad168** [ivan-hc/Steam-appimage#36]
I use `box64` cannot run your appimage on ARM linux🤭
```
localhost ~ [SIGBUS]> box64 ./Steam-1.0.0.81-2-3-x86_64.AppImage
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL SHA1 SHA2 USCAT FLAGM FLAGM2 FRINT PageSize:4096 Running on unknown aarch64 cpu with 9 Cores
Params database has 46 entries
Box64 with Dynarec v0.2.7 a891e1f8 built on Jan  6 2024 01:22:36
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 28 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/:/snap/bin/:/data/data/com.termux/files/usr/bin/:/system/bin/:/system/xbin/
Looking for ./Steam-1.0.0.81-2-3-x86_64.AppImage
Rename process to "Steam-1.0.0.81-2-3-x86_64.AppImage"
Error: Unsupported Syscall 0x13h (19)
```

**Comment by Samueru-sama** [comment]
Unfortunately Conty seems to only support x86_64, and the base of Conty which is Archlinux doesn't have official arm builds yet either. 

With that said there a flicker of hope and that is @Azathothas

**Comment by iHad168** [comment]
We not need ARM version Arch
Because very much game is x86
Only need run on ARM device
I will try ask Box64 and Conty developer
Can you tell me If i not use conty
Can i get steam and all package in your appimage?
Because i only need run linux version steam in `termux` android
But android very much is ARM

**Comment by Samueru-sama** [comment]
> Can you tell me If i not use conty Can i get steam and all package in your appimage?

I'm not sure what you meant here.

**Comment by iHad168** [comment]
> I'm not sure what you meant here.

I mean, is there any way can Extract Steam and Steam necessary Libs Package?
I think If i don’t use Conty if i can run Steam?

**Comment by Samueru-sama** [comment]
> > I'm not sure what you meant here.
> 
> I mean, is there any way can Extract Steam and Steam necessary Libs Package? I think If i don’t use Conty if i can run Steam?

You can use `--appimage-extract` to extract the appimage, but that will leave you with the conty container and I'm not sure how to extract what is in the conty container though.

**Comment by ivan-hc** [comment]
to extract the content of conty.sh, run `./conty.sh -e`, however recompression is not supported, nor there is a known way to run files from it (maybe you need to use `chroot`).

**Comment by Azathothas** [comment]
> Unfortunately Conty seems to only support x86_64, and the base of Conty which is Archlinux doesn't have official arm builds yet either.
> 
> With that said there a flicker of hope and that is @Azathothas

I spent an entire day to port [flatimages](https://github.com/ruanformigoni/flatimage) to arm, only to realize there's no steam for arm:
https://github.com/ValveSoftware/steam-for-linux/issues/4061
