### ISSUE TITLE
Bundle more fonts in?

### ISSUE THREAD

**Issue by jwnhy** [ivan-hc/Steam-appimage#37]
It seems that this arch-chroot only bundles in Latin-based (not sure if this is the correct wordy) font and does not include CJK fonts, e.g., wqy-microhei.

This causes problems if the game relies on such font, e.g., RimWorld relies on wqy-microhei.

My current fix is to fork my version and add two packages in the script, wqy-zenhei and wqy-microhei. (it didn't increase the final blob size)

I wonder if you want to merge this, as this is specific to Chinese...

If this can include a minimal set of fonts for most languages, that would be splendid.

**Comment by Samueru-sama** [comment]
I think a better solution is to bind mount the users fonts like we already do with the locales @ivan-hc

**Comment by ivan-hc** [comment]
it is enough to add this line to the AppRun
```
--bind-try /usr/share/themes /usr/share/themes
```
the AppRun should look like this then
```
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
"${HERE}"/conty.sh --bind-try /usr/share/themes /usr/share/themes steam-screensaver-fix-runtime "$@"
```
@Samueru-sama however, some windows programs or games may not find the correct font if not installed on the host.

What do you think about?

**Comment by jwnhy** [comment]
Thanks! Glad to see there is a general solution!

**Comment by Samueru-sama** [comment]
@jwnhy can you try doing what Ivan suggested? the steps are: 

```
 ./Steam-1.0.0.81-2-3-x86_64.AppImage --appimage-extract
```

Then edit `./squasfs-root/AppRun` to look like what Ivan pasted: 

```
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
"${HERE}"/conty.sh --bind-try /usr/share/fonts /usr/share/fonts steam-screensaver-fix-runtime "$@"
```

Let me know if the font issue gets fixed.

**Comment by ivan-hc** [comment]
@Samueru-sama if it is so, you should also remove the ttf-fonts* references among dependences... or at least ad a `rm -rf "&{bootstrap}"/usr/share/fonts/*`

**Comment by Samueru-sama** [comment]
> @Samueru-sama if it is so, you should also remove the ttf-fonts* references among dependences... or at least ad a `rm -rf "&{bootstrap}"/usr/share/fonts/*`

[I did that already](https://github.com/Samueru-sama/Steam-appimage/commit/cba1caddce4fbab90e317cf91a572ac1ed615fc6)

Originally deleted the entire dir but that let to mkdir read only filesystem errors.

**Comment by ivan-hc** [comment]
OK, I was not aware of the "test" branch

**Comment by jwnhy** [comment]
@Samueru-sama I just tested https://github.com/Samueru-sama/Steam-appimage/releases/tag/continuous

It works well for RimWorld, I think the fix is taking effect.
Haven't been able to test the "extract" though.

**Comment by Samueru-sama** [comment]
> @Samueru-sama I just tested https://github.com/Samueru-sama/Steam-appimage/releases/tag/continuous
> 
> It works well for RimWorld, I think the fix is taking effect. Haven't been able to test the "extract" though.

you don't have to test the extract, the changes I made in the AppImage I linked do all of that. 

@ivan-hc do you want me to PR that or would you prefer to modify the conty of steam to automatically add the bind mount for /`usr/share/fonts` as right now my current changes would modify the `AppRun`.

**Comment by ivan-hc** [comment]
do the PR, I need to keep the script "conty-start" on my fork as much in-line with upstream as possible
