### ISSUE TITLE
"fuse: failed to exec fusermount: Permission denied"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ivan-hc/Steam-appimage#5]
```
$ chmod u+x Steam-1.0.0.79-2-x86_86.AppImage 
$ ./Steam-1.0.0.79-2-x86_86.AppImage 
fuse: failed to exec fusermount: Permission denied

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```

**Comment by ivan-hc** [comment]
Hi, this message appears because thi AppImage forks with fuse3

**Comment by Samueru-sama** [comment]
Are you using gentoo? You might be affected by a bug in the new runtime. 

[There is actually a fix in the works](https://github.com/AppImage/type2-runtime/pull/32), but it is taking a while for it to be merged.

**Comment by Samueru-sama** [comment]
This other trick might work in the meantime, if it works you don't have to be messing with `/usr/bin/fusermount`

`FUSERMOUNT_PROG=$(which fusermount) ./Steam-1.0.0.79-2-x86_86.AppImage`

`FUSERMOUNT_PROG` can be defined in your bash_profile or zprofile, etc btw.

**Comment by vitaly-zdanevich** [comment]
> FUSERMOUNT_PROG=$(which fusermount) ./Steam-1.0.0.79-2-x86_86.AppImage

Now it run, thanks.
