### ISSUE TITLE
Default installation dir is /tmp

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ivan-hc/Steam-appimage#6]
![image](https://github.com/user-attachments/assets/9d120793-0e44-4c6e-aff2-06fcb8b70be3)

And I do not see how I can change it - this screen is empty, nothing on "NEW FOLDER..." and "SELECT"

![image](https://github.com/user-attachments/assets/6c70d165-75d1-4650-94a9-9121e1dbc1a8)

**Comment by Samueru-sama** [comment]
That's weird, I cannot replicate the issue. 

![image](https://github.com/user-attachments/assets/a50717d7-6341-489a-97a9-80e9c5bf944b)

I even deleted my `$XDG_DATA_HOME/Steam` directory and relaunched steam, which basically installs it from 0, and the first thing it tries to use to install is my home: 

![image](https://github.com/user-attachments/assets/babf6050-5eb1-4026-bc2f-9025dd99a066)

**Comment by Samueru-sama** [comment]
I also got help getting the appimage tested on a fresh archlinux install and the issue can't be replicated there either.

![image](https://github.com/user-attachments/assets/d0caa0b9-24b8-408a-9318-99b495f8974c)

**Comment by ivan-hc** [comment]
May this would happen because @vitaly-zdanevich uses a non-systemd distro?

**Comment by ivan-hc** [comment]
@vitaly-zdanevich I've seen that you're also a Conty user, so is this happening also with Conty?

**Comment by vitaly-zdanevich** [comment]
The same issue in Conty
![image](https://github.com/user-attachments/assets/1576153e-6f72-4224-bc14-af961caf4e52)

Yes I have no systemd.

**Comment by Samueru-sama** [comment]
> May this would happen because @vitaly-zdanevich uses a non-systemd distro?

I'm on Artix-runit so it isn't that.

**Comment by ivan-hc** [comment]
may this be an issue with XDG directories?

**Comment by Samueru-sama** [comment]
> may this be an issue with XDG directories?

The only way would be is if `XDG_DATA_HOME` were to be defined as /tmp, which would make no sense. 

@vitaly-zdanevich Add this to your bash_profile or zprofile: 

`export XDG_DATA_HOME="$HOME/.local/share"`

**Comment by vitaly-zdanevich** [comment]
Thanks, I tried - the same :(

**Comment by Kron4ek** [comment]
As we found out, it shows `/tmp` but installs games to `~/.local/share/Steam/steamapps` anyway. So i'd say this is confusing, but not too critical.

**Comment by Samueru-sama** [comment]
But why does it happen? I wasn't able to replicate that on 2 different systems.

**Comment by Kron4ek** [comment]
I wasn't able either, my guess is that it shows the partition with the most free space available.

1 августа 2024 г. 20:13:59 GMT+05:00, Samuel ***@***.***> пишет:

**Comment by vitaly-zdanevich** [comment]
But /tmp is not an ext4 partition - just a folder on my Gentoo Linux.

**Comment by Samueru-sama** [comment]
> But /tmp is not an ext4 partition - just a folder on my Gentoo Linux.

Can I see your `/etc/fstab`?

**Comment by vitaly-zdanevich** [comment]
```
$ cat /etc/fstab
# /etc/fstab: static file system information.
#
# noatime turns off atimes for increased performance (atimes normally aren't 
# needed); notail increases performance of ReiserFS (at the expense of storage 
# efficiency).  It's safe to drop the noatime options if you want and to 
# switch between notail / tail freely.
#
# The root filesystem should have a pass number of either 0 or 1.
# All other filesystems should have a pass number of 0 or greater than 1.
#
# See the manpage fstab(5) for more information.
#

# <fs>			<mountpoint>	<type>		<opts>		<dump/pass>

# NOTE: If your BOOT partition is ReiserFS, add the notail option to opts.
#
# NOTE: Even though we list ext4 as the type here, it will work with ext2/ext3
#       filesystems.  This just tells the kernel to use the ext4 driver.
#
# NOTE: You can use full paths to devices like /dev/sda3, but it is often
#       more reliable to use filesystem labels or UUIDs. See your filesystem
#       documentation for details on setting a label. To obtain the UUID, use
#       the blkid(8) command.

UUID=f4936ae5-f2c9-4997-9bd0-d3991859f3c6	/		ext4		noatime 0 1
```

**Comment by Samueru-sama** [comment]
@vitaly-zdanevich That's all your fstab? you don't have /tmp on tmpfs, the poor ssd has been getting hammered with unnecessary writes lol

Add something like this to the fstab: 

`tmpfs   /tmp         tmpfs   rw,noatime,size=20G          0  0`

Something like this because I use tmpfs for a lot of stuff on my setup, that is why it is massive, I even have `$XDG_CACHE_HOME` on a user owned directory in /tmp.

**Comment by vitaly-zdanevich** [comment]
Hm, is tmpfs good for system performance?

**Comment by Samueru-sama** [comment]
> Hm, is tmpfs good for system performance?

Absolutely and it is good for the lifespan of your ssd. [The gentoo wiki has a nice article on it](https://wiki.gentoo.org/wiki/SSD#Reducing_amount_of_writes)

**Comment by vitaly-zdanevich** [comment]
Added to fstab, deleted folder, now I see this:

![image](https://github.com/user-attachments/assets/c425932a-6e7d-4d81-b571-95e34d69afd6)


And still empty screen for folder change.

The same for Conty.

**Comment by Samueru-sama** [comment]
Good, the main issue is solved.

> And still empty screen for folder change.

I just checked the GUI have the same issue as you that using select does nothing.

**I even installed the Steam arch package on my PC and I still have the issue** lol

![image](https://github.com/user-attachments/assets/ef0da989-7642-4764-ace6-72deb9fd212a)

This is an Steam issue.

I personally symlink what would be my `~/.local/bin/Steam` directory to another partition in my ssd, that way I pretty much achieve the same result as messing with the Steam configuration and changing where to install games.

**Comment by Samueru-sama** [comment]
Alright, I think I found out why the issue happens. 

I need to have `xdg-desktop-portal-gtk` for this work... this affects the arch steam package and this appimage since it isn't marked as a dependency of Steam.

Steam used to have this native but it seems they got rid of it LOL.

**Comment by Samueru-sama** [comment]
@vitaly-zdanevich The issue will be fixed once #13 gets merged and we figure out why the CI suddenly decided to break wtf. 

In the meantime you can install the portable in gentoo and it will work.

**Comment by Samueru-sama** [comment]
@vitaly-zdanevich can you try this appimage? https://github.com/Samueru-sama/Steam-appimage/releases/tag/continuous

I've bundled xdg-desktop-portal-gtk but turns out that it doesn't work, it needs to be on the host for some reason.

If I can't find a way to get the portal to work in the appimage then I don't see a point in bundling in it.

**Comment by ivan-hc** [comment]
@Samueru-sama discord

**Comment by vitaly-zdanevich** [comment]
> In the meantime you can install the portal in gentoo and it will work.

Thanks, but I see it want too many dependencies - Steam already works for me <3

**Comment by Samueru-sama** [comment]
> > In the meantime you can install the portal in gentoo and it will work.
> 
> Thanks, but I see it want too many dependencies - Steam already works for me <3

What do you mean by it already works? 

Did you test this other appimage? https://github.com/Samueru-sama/Steam-appimage/releases/tag/continuous

I bundled the portal into it, let me know if you can choose a different directory on the Steam interface, I didn't work for me but who knows if it does for you.

Also on arch this is all the dependencies that `xdg-desktop-portal-gtk` needs: 

`geoclue-2.7.1-3  rtkit-0.13-2.1  xdg-desktop-portal-1.18.4-1  xdg-desktop-portal-gtk-1.15.1-2`

which is 4.17 MiB total.

**Comment by vitaly-zdanevich** [comment]
> Also on arch this is all the dependencies that `xdg-desktop-portal-gtk` needs:

Ops not many deps but I do not want to install Pipewire:

```
# emerge -a xdg-desktop-portal-gtk

These are the packages that would be merged, in order:

Calculating dependencies... done!
Dependency resolution took 2.01 s (backtrack: 0/20).


!!! The ebuild selected to satisfy ">=media-video/pipewire-0.3:=" has unmet requirements.
- media-video/pipewire-1.0.7-r1::gentoo USE="X bluetooth dbus ffmpeg readline ssl v4l -doc -echo-cancel -extra -flatpak -gsettings -gstreamer -ieee1394 -jack-client -jack-sdk -liblc3 -lv2 -man -modemmanager -pipewire-alsa -roc (-selinux) -sound-server (-system-service) -systemd -test -zeroconf"

  The following REQUIRED_USE flag constraints are unsatisfied:
    ffmpeg? ( extra )

  The above constraints are a subset of the following complete expression:
    ffmpeg? ( extra ) bluetooth? ( dbus ) jack-sdk? ( !jack-client ) modemmanager? ( bluetooth ) system-service? ( systemd ) !sound-server? ( !pipewire-alsa ) jack-client? ( dbus )

(dependency required by "sys-apps/xdg-desktop-portal-1.18.4::gentoo" [ebuild])
(dependency required by "sys-apps/xdg-desktop-portal-gtk-1.14.1::gentoo" [ebuild])
(dependency required by "xdg-desktop-portal-gtk" [argument])
```

**Comment by vitaly-zdanevich** [comment]
> Did you test this other appimage? https://github.com/Samueru-sama/Steam-appimage/releases/tag/continuous

Still empty screen of the storing location choosing.

**Comment by vitaly-zdanevich** [comment]
Offtopic question - is this project and Conty the only projects that wrap Steam with dependencies? No competitors?

**Comment by ivan-hc** [comment]
> Offtopic question - is this project and Conty the only projects that wrap Steam with dependencies? No competitors?

Flatpak

**Comment by Samueru-sama** [comment]
> > Did you test this other appimage? https://github.com/Samueru-sama/Steam-appimage/releases/tag/continuous
> 
> Still empty screen of the storing location choosing.

Yeah, it seems the only way is by having the `xdg-desktop-portal-gtk` installed. 

If you are using KDE, then use the `xdg-desktop-portal-kde`, etc.

>Offtopic question - is this project and Conty the only projects that wrap Steam with dependencies? No competitors?

flatpak and snap are the others, the steam snap didn't have a working proton until like a few days ago lol.

Also the xdg-desktop-portal is a dependency of flatpak.
